config/routes.rb
Rails.application.routes.draw do
  
  #App core mappgins
  get 'sessions/new'
  root 'home#home'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #Student mappings  
  get 'students' => 'students#new'
  
  #lecturer mappings
  get 'lecturer' => 'lecturer#new'
  post 'lecturer_search_student' => 'lecturer#searchStudent'
  
  #admin mappings
  get 'admin' => 'admin#new'
  get 'admin_create_course' => 'admin#create_course'
  post 'admin_submit_course' => 'admin#submit_course'
  
  resources :users
  #resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 50 }
    validates :semester,  presence: true, length: { maximum: 2 }
    
    
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
     validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    has_one :student
    #if need it add for other one to one relationships with the other types of users:
    #has_one :lecturer
    #has_one :admin
    #and their respectives belong_to :user , on each of those linked classes

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    #GET ends up here
    def create_course
        render 'create_course'
    end
    
    #POST ends up here: Submit a created course to db, comes from create_course view (create_course.html.erb)
    def submit_course
        if(!(params[:name].blank?) && !(params[:semester].blank?))
        @course = Course.new
        @course.name = params[:name]
        @course.semester = params[:semester]
        @course.lecturer_id = 0
            if @course.save
            #If saved succesfully, according to the type of user, redirect to the login page, inform before with flash message
            flash[:success] = "Course Created!" 
            redirect_to admin_create_course_path(@get)
            end
        else
            flash[:danger] = "Course cannot be created, input correct fields!" 
            redirect_to admin_create_course_path(@get)
        end
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
    end    
    
    
end

app/controllers/lecturer_controller.rb
class LecturerController < ApplicationController
    #Mapping for route post on this resource, on: lecturer#searchStudent @see routes.rb
    #If a search is conducted, for students, from lecturer/new.erb.html, it will hit this method.
    def searchStudent
        #Retrieve students from DB according to search criteria passed from View 
        #(GET->Lecturers#new.html.erb->Post->This controller)
        
        if(!(params[:searchName].blank?))
            #If we have a name inputted, fire the query
            @students = User.where("name LIKE ? and user_type LIKE 'Student'", "%#{params[:searchName]}%")
        elsif(!(params[:searchRegId].blank?))
            #If not we might have a registration id passed
            @students = User.where(" user_id = ? and user_type LIKE 'Student'", params[:searchRegId])
        else
            #Otherwise just display a message of no results found 
            @students = []
        end
        #Render the view for displaying results of model retrieved
        render 'student_search'
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    current_user
  end

  def create
    #pull user out of the db and authenticate with password
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirectToUserTypePage(user)
    else
      #If doesn't authenticate, redirect to new html (render instruction) and display the error message
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
  private
  
  def redirectToUserTypePage(user)
        if(user.user_type == "Student")
            redirect_to students_path(@get)
        elsif(user.user_type == "Lecturer")
            redirect_to lecturer_path(@get)
        else
            redirect_to admin_path(@get)
        end
  end
  
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    #GET method mapping for /users creates a NEW User object
    def new
        #Create a user model object and redirect to the view that holds the form
        @user = User.new
    end
    
    #POST method mapping, the object created above is persisted in DB here.
    def create
    @user = User.new(user_params) #this needed for validating the form fields values received in the post body request    #@user.type = selectedType    
        #If valid fields, persist to DB
        if @user.save
            create_related_user
          #If saved succesfully, according to the type of user, redirect to the login page, inform before with flash message
         flash[:success] = "You just signed up, please log in!" 
         redirect_to login_path(@get)
        else
          render 'new'
        end
    end
    
    
    private
    #Method handles the calling to the class fields validations
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :user_type)
    end
    
    def create_related_user
        if(@user.user_type == "Student")
            #create the student object and save to db
            #assign related application user_id from user just created, create the link between the entities
            student = Student.new
            student.user_id = @user.user_id
            student.save
        end
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Academic Courses Application"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lecturer_helper.rb
module LecturerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # This places a temporary cookie on the user’s browser containing an encrypted version of the user’s id, 
    # which allows us to retrieve the id on subsequent pages using session[:user_id].
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= User.find_by(user_id: session[:user_id])
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
    # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/create_course.html.erb
<% provide(:title, 'Create Course') %>
<h1>Admin Actions</h1>

<h3>Create Course</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(admin_submit_course_path, :method => "post", id: "create-course-form") do %>
    
    <p>Name: <%= text_field_tag :name, nil, class: 'form-control' %></p>
    <p>Semester: <%= text_field_tag :semester, nil, class: 'form-control' %></p>    
   
    <%= submit_tag "Create", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/admin/new.html.erb
<h1>Admin Actions</h1>

<h3>Create Course Modules</h3>
<%= form_tag(admin_create_course_path, :method => "get", id: "search-form") do %>
    <%= submit_tag "Select" %>
<% end %>

app/views/home/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
  </head>
  <body>
    <h1>Academic Courses</h1>
    <p>
      This is the home page for the
      application.
    </p>
  </body>
</html>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Academic Courses Application", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign Up!", signup_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Academic Courses Application</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</body>
</html>

app/views/lecturer/new.html.erb
<h1>Lecturer's Main Page</h1>

<h3>Search a Student:</h3>
<%= form_tag(lecturer_search_student_path, :method => "post", id: "search-form") do %>
    <p>Name: <%= text_field_tag :searchName, nil %></p>
    <p>Registrarion Id: <%= text_field_tag :searchRegId, nil %></p>
    <%= submit_tag "Search" %>
<% end %>

app/views/lecturer/student_search.html.erb
<h2>Lecturer: Search for Student</h2>
<p>Students found:</p>

<!-- loop through word elements -->
<% @students.each do |student|  %>
    <!-- display Student info -->
    <p>  <%= student["name"] %> ,  Email:  <%= student["email"] %> </p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
     
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
            
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label "Type of User" %>
      <%= f.select :user_type, [["Student","Student"],["Lecturer","Lecturer"],["Admin","Admin"]] %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>